# Generated by Django 2.2.6 on 2019-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=3000, max_length=200),
            preserve_default=False,
        ),
    ]
